default: &default
  adapter: postgresql
  encoding: unicode
  username: positiondev
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_testing_development

test:
  <<: *default
  database: rails_testing_test

production:
  <<: *default
  database: rails_testing_production
  username: positiondev
  password: 
